### ISSUE TITLE
Orange Pi Support.

### ISSUE THREAD

**Issue by RaptorHunterMZ** [linux-paul/OctoPrint-Heatbedsavety#2]
Could you add support to orange pi? when I install the plugin I don't see the plugin anywhere in octoprint.

**Comment by linux-paul** [comment]
Unfortunately I'm not experienced with orange pi, but I'll see what I can do.
If neither the plugin's sidebar nor settings screen is visible, there went something wrong while loading the plugin and should be logged to octoprints log. Can you provide the data?
I expect there is some trouble loading python's GPIO lib or init the default pin.

**Comment by linux-paul** [comment]
Reviewing the orange pi python GPIO tutorials  show some differences to raspberry pi e.g. http://codelectron.com/blink-leds-using-orange-pi-zero-gpio-and-python/. The simpest way is to change the necessary lines yourself, are you able to achive this? . I'd not like to implement a hardware detection with depending initialisation.

**Comment by RaptorHunterMZ** [comment]
> 
> 
> Reviewing the orange pi python GPIO tutorials show some differences to raspberry pi e.g. http://codelectron.com/blink-leds-using-orange-pi-zero-gpio-and-python/. The simpest way is to change the necessary lines yourself, are you able to achive this? . I'd not like to implement a hardware detection with depending initialisation.

I can't do any programing, but I am using WiringOP https://github.com/zhaolei/WiringOP for the PSU control plugin, I just have to change the pins to out.

**Comment by linux-paul** [comment]
This repo now provides an orangepi branch. Download zip and try to install the plugin localy. Unfortunately I can't test this code because I haven't an orangePi. Default Port is PD12.

**Comment by RaptorHunterMZ** [comment]
Thanks for the update, sorry to be bothering you with more requests. I would like to use **pin 28**. After installing wiring OP I use **gpio write 28 off** to turn the bed on (because of the logic of the relay), and **gpio write 28 on** to turn the heated bed, in **/etc/default/octoprint** I added the following lines so when octoprint starts the pins are configured. 
gpio write 29 on _- turn power supply off_ 
gpio write 28 on _- turn heated bed off_ 
gpio mode 29 out _- convert PIN29 (RxD1 on the board) to out_
gpio mode 28 out _- convert PIN28 (TxD1 on the board) to out_
i don't know if this is helpful at all, but it's working with PSU control, without any direct support for the orange pi boards.

**Comment by linux-paul** [comment]
OK wiringPI obviously needs another library but I didn't get the naming of the GPIOs right now. Also driving an output to high to switch the bedpower of is very unsual. In case of connection problems the bedpower ist always connected -> bad idea. If you took alook to the limit switches, they are also designed as opener. I use a PSU control via RaspberryPI overlays.
Due to these special requirements and my limited possibilities regarding hardware and OS, I cannot provide further support.
Please take a look to this pages https://docs.octoprint.org/en/master/plugins/gettingstarted.html.  As you finished cheapter1 you should be able to implement a solution which meets your requirements. 
Sorry

Edit: Comparing the __init__py and setup.py scripts of each branch shows the changes in GPIO control I made.
